apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m5.medium", "c3.medium","c4.medium","c5.medium"]
    desiredCapacity: 1
    spot: true