apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["r6g.medium", "c7gd.medium","c7gd.medium","c7gd.medium"]
    desiredCapacity: 2
    spot: true